"use client";
import Link from "next/link";import { useState } from "react";import { ArrowRight,Building2,Camera,Check,FileCheck2,Headphones,Map,ShieldCheck,UserRound } from "lucide-react";import { services,qualityItems,useCases } from "@/content/site";import { brand } from "@/config/brand";import { testimonials } from "@/data/testimonials";import { SectionHeading } from "@/components/ui/SectionHeading";
export function TrustStrip(){const items=[[Headphones,"Équipe joignable"],[UserRound,"Convoyeurs sélectionnés"],[Camera,"État des lieux documenté"],[FileCheck2,"Suivi de mission"],[Map,"Couverture nationale"]] as const;return <div className="trust-strip">{items.map(([I,t])=><div key={t}><I/><span>{t}</span></div>)}</div>}
export function AudienceSelector(){return <section className="audiences"><article><span>Pour vos opérations</span><Building2/><h2>Vous êtes professionnel</h2><p>Transferts inter-sites, livraisons clients, restitutions ou mouvements de flotte : déléguez vos missions sans mobiliser vos équipes.</p><Link href="/professionnels">Découvrir les solutions entreprises <ArrowRight/></Link></article><article className="light"><span>Pour votre véhicule</span><UserRound/><h2>Vous êtes particulier</h2><p>Achat à distance, déménagement ou restitution : nous organisons le déplacement de votre véhicule de porte à porte.</p><Link href="/particuliers">Déplacer mon véhicule <ArrowRight/></Link></article></section>}
export function ServicesGrid(){return <div className="service-grid">{services.filter(s=>s.enabled).map((s,i)=><article key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div>}
export function ProcessTimeline(){const steps=[["Votre demande","Indiquez le trajet, le véhicule et la date souhaitée. Notre équipe vérifie la faisabilité et vous recontacte."],["L’affectation","Nous sélectionnons un convoyeur adapté et coordonnons les rendez-vous."],["Le suivi","La prise en charge, l’état des lieux et les étapes importantes sont documentés."],["La livraison","Le véhicule est remis au destinataire et les documents de fin de mission sont centralisés."]];return <div className="timeline">{steps.map((s,i)=><article key={s[0]}><span>0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div></article>)}</div>}
export function QualityPanel(){return <div className="quality-grid"><div className="tablet-demo"><span>Exemple d’interface</span><div className="vehicle-line"><div/><p>État des lieux<br/><small>Contrôle au départ</small></p><strong>Validé</strong></div><div className="photo-row"><i/><i/><i/></div><p><Check/> Documents centralisés</p></div><div><SectionHeading eyebrow="Qualité & sécurité" title="Chaque étape documentée."/><ul className="check-list">{qualityItems.filter(i=>i.enabled).map(i=><li key={i.label}><Check/>{i.label}</li>)}</ul><Link className="text-link" href="/qualite-securite">Découvrir notre exigence qualité <ArrowRight/></Link></div></div>}
export function UseCases(){const [active,setActive]=useState(0),item=useCases[active];return <div className="use-cases"><div className="case-tabs" role="tablist" aria-label="Cas d’usage">{useCases.map((c,i)=><button role="tab" aria-selected={active===i} onClick={()=>setActive(i)} key={c.name}>{c.name}</button>)}</div><article><div><small>Le besoin</small><p>{item.problem}</p></div><div><small>Notre réponse</small><p>{item.response}</p></div><div><small>Le bénéfice</small><p>{item.benefit}</p></div><Link href="/devis">Parler de votre besoin <ArrowRight/></Link></article></div>}
export function ConditionalSocialProof(){const has=testimonials.some(t=>t.authorized)||brand.customerLogos.length||brand.verifiedStats.length;if(has)return <section>{/* Données vérifiées rendues ici lorsqu'elles sont configurées. */}</section>;return <div className="method-proof"><ShieldCheck/><div><h3>Une exigence constante, pour un véhicule comme pour une flotte.</h3><p>Un interlocuteur responsable, un protocole clair et une mission documentée du départ à la livraison.</p></div></div>}
export function HumanResponse(){const configured=brand.businessHours.length>0;return <section className="human"><div><span className="eyebrow light-eye">Contact direct</span><h2>Une équipe qui répond vraiment.</h2><p>Une mission urgente ne doit pas devenir une chaîne d’appels. Votre demande est prise en charge par une équipe identifiable, responsable de son organisation jusqu’à la livraison.</p></div><div className="human-card"><p><span className={`availability ${configured?"open":""}`}/>{configured?"Horaires configurés":"Demandez un rappel"}</p>{brand.phone&&<a href={`tel:${brand.phone}`}>{brand.phone}</a>}<Link className="btn ivory" href="/contact">Être rappelé</Link></div></section>}
