"use client";
import { useState } from "react";import { ArrowLeft,ArrowRight,Check } from "lucide-react";import type { QuoteData } from "@/lib/validation";
type Data=Partial<QuoteData>;const labels=["Profil","Trajet","Véhicule","Mission","Coordonnées","Résumé"];
export function QuoteWizard(){const [step,setStep]=useState(0),[data,setData]=useState<Data>({running:"Oui"}),[errors,setErrors]=useState<Record<string,string>>({}),[status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");const set=(k:keyof Data,v:string|boolean)=>setData(d=>({...d,[k]:v}));
const validate=()=>{const fields=["profile",...(step===1?["departure","arrival"]:[]),...(step===2?["vehicle","running"]:[]),...(step===3?["date"]:[]),...(step===4?["name","phone","email","consent"]:[])];const e:Record<string,string>={};fields.forEach(k=>{if(!data[k as keyof Data])e[k]="Ce champ est requis"});if(step===4&&data.email&&!/^[^@]+@[^@]+\.[^@]+$/.test(data.email))e.email="Adresse e-mail invalide";setErrors(e);return !Object.keys(e).length};const next=()=>{if(validate())setStep(s=>Math.min(5,s+1))};const submit=async()=>{setStatus("sending");const res=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const out=await res.json();setStatus(out.ok?"success":"error")};
if(status==="success")return <div className="form-success" aria-live="polite"><Check/><h2>Votre demande a bien été transmise.</h2><p>Les informations de votre trajet sont enregistrées. Notre équipe reviendra vers vous après vérification.</p></div>;
return <div className="wizard"><div className="progress" aria-label={`Étape ${step+1} sur 6`}><span style={{width:`${((step+1)/6)*100}%`}}/></div><div className="step-labels">{labels.map((l,i)=><span key={l} className={i===step?"active":""}>{i+1}. {l}</span>)}</div><div className="form-step">
{step===0&&<><h2>Vous êtes…</h2><div className="choice-grid">{["Entreprise","Particulier"].map(v=><button className={data.profile===v?"selected":""} key={v} onClick={()=>set("profile",v)}>{v}</button>)}</div><Err name="profile" errors={errors}/></>}
{step===1&&<><h2>Quel trajet devons-nous organiser ?</h2><Field label="Adresse de départ" name="departure" value={data.departure} set={set} error={errors.departure}/><Field label="Adresse d’arrivée" name="arrival" value={data.arrival} set={set} error={errors.arrival}/></>}
{step===2&&<><h2>Parlez-nous du véhicule</h2><Field label="Catégorie, marque et modèle" name="vehicle" value={data.vehicle} set={set} error={errors.vehicle}/><fieldset><legend>Le véhicule est-il roulant ?</legend><div className="radio-row">{["Oui","Non"].map(v=><label key={v}><input type="radio" checked={data.running===v} onChange={()=>set("running",v)}/>{v}</label>)}</div></fieldset></>}
{step===3&&<><h2>Quand souhaitez-vous le déplacer ?</h2><Field label="Date souhaitée" name="date" type="date" value={data.date} set={set} error={errors.date}/><Field label="Précisions ou services complémentaires (facultatif)" name="comment" value={data.comment} set={set}/></>}
{step===4&&<><h2>Comment vous recontacter ?</h2><div className="two-fields"><Field label="Nom" name="name" value={data.name} set={set} error={errors.name}/><Field label="Société (facultatif)" name="company" value={data.company} set={set}/></div><div className="two-fields"><Field label="Téléphone" name="phone" type="tel" value={data.phone} set={set} error={errors.phone}/><Field label="E-mail" name="email" type="email" value={data.email} set={set} error={errors.email}/></div><label className="consent"><input type="checkbox" checked={data.consent??false} onChange={e=>set("consent",e.target.checked)}/>J’accepte que mes informations soient utilisées pour répondre à ma demande.</label><Err name="consent" errors={errors}/></>}
{step===5&&<><h2>Vérifiez votre demande</h2><dl className="summary"><div><dt>Profil</dt><dd>{data.profile}</dd></div><div><dt>Trajet</dt><dd>{data.departure} → {data.arrival}</dd></div><div><dt>Véhicule</dt><dd>{data.vehicle} — roulant : {data.running}</dd></div><div><dt>Date</dt><dd>{data.date}</dd></div><div><dt>Contact</dt><dd>{data.name} · {data.phone} · {data.email}</dd></div></dl>{status==="error"&&<p className="error" role="alert">La transmission a échoué. Le formulaire n’est peut-être pas encore connecté ; utilisez la page contact.</p>}</>}
</div><div className="wizard-actions">{step>0&&<button className="btn secondary" onClick={()=>setStep(s=>s-1)}><ArrowLeft/>Retour</button>}{step<5?<button className="btn primary" onClick={next}>Continuer<ArrowRight/></button>:<button className="btn primary" disabled={status==="sending"} onClick={submit}>{status==="sending"?"Transmission…":"Transmettre ma demande"}</button>}</div></div>}
function Err({name,errors}:{name:string;errors:Record<string,string>}){return errors[name]?<p className="field-error" role="alert">{errors[name]}</p>:null}
function Field({label,name,value,set,error,type="text"}:{label:string;name:keyof Data;value?:string;set:(k:keyof Data,v:string)=>void;error?:string;type?:string}){return <label className="field">{label}<input type={type} value={value??""} onChange={e=>set(name,e.target.value)} aria-invalid={!!error}/>{error&&<span className="field-error">{error}</span>}</label>}
